modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="pmmo_atm10"
version="1.0.0"
displayName="ProjectMMO-ATM10"
displayURL=""
credits=""
authors="James Burlison, Cory Burlison"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.pmmo_atm10]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.pmmo_atm10]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.pmmo_atm10]]
    modId = "puffish_skills"
    type="required"
    versionRange = "[0.15.1,)"
    ordering="AFTER"

[[dependencies.pmmo_atm10]]
    modId = "pmmo"
    type="required"
    versionRange = "[1.21.1,)"
    ordering="AFTER"

[[dependencies.pmmo_atm10]]
    modId = "puffish_attributes"
    type="required"
    versionRange = "[0.7.2,)"
    ordering="AFTER"

[[dependencies.pmmo_atm10]]
    modId = "pufferfish_unofficial_additions"
    type="required"
    versionRange = "[2.2.4,)"
    ordering="AFTER"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration